theme: jekyll-theme-minimal
title: Ricardo Luís Bertolucci Filho
description: Master's in Mathematics (Functional Analysis and Operator Theory) and Data Scientist. Showcasing projects in programming, data science, and mathematics.
logo: /assets/img/logo.png # Optional: Add your logo path if you have one
show_downloads: false

# Author information
author:
  name: Ricardo Luís Bertolucci Filho

# Social links
github_username: ric-rky
linkedin_username: ricardo-luís-bertolucci-filho

# Additional settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optional: Navigation
# You can add custom navigation here later